shared:
  image: node:8

annotations:
  screwdriver.cd/chainPR: true

jobs:
  first-job:
    requires: [~pr, ~commit]
    steps:
      - echo: echo "this is first job. Hello World 123!"
  second-job:
    requires: [first-job]
    steps:
      - echo: echo "this is second job."
  random-job:
    requires: [second-job]
    steps:
      - echo: echo "this is random job."
